### ISSUE TITLE
[feat] ScrollView 구현(Default 이슈 템플릿 테스팅)

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [jeong-hyeonHwang/Git-Convention#1]
### 작업에 대한 간단한 설명
- 코드 기반으로 ScrollView를 구현합니다.

### TODO
- [ ] ScrollView Constraints 설정
- [ ] ScrollView 색상 설정
- [ ] ScrollView 내부 Component 설정

### 작업 일정(Optional)
2022.10.14 - 2022.10.14 (작업일자)

|작업일자|작업 내용|
|:---:|:---:|
|2022.10.14|ScrollView Constraints 설정|
|2022.10.14|ScrollView 색상 설정|
|2022.10.14|ScrollView 내부 Component 설정|

### Optional
- `본 이슈는 이슈 템플릿 테스팅을 위한 이슈입니다.`

**Comment by LeeSungNo-ian** [comment]
엘리제! 연결 된 이슈가 없네요?

확인 부탁드립니다 👀..
